EEEEEE
======================================================================
ERROR: test_list_int (__main__.Test01_AddContact)
*** Test01 *** GIVEN: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates']} AND contacts = Contacts(filename='t99.dat') *** FUNCTION CALL: contacts.add_contact(id = '7145551212', first_name = 'Richard', last_name = 'Stallman') *** EXPECT: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates'], '7145551212': ['Richard', 'Stallman']} ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\edmar\OneDrive\Documents\CSUF Fall 2024\Python\Assignments\Assignment 7\lab07-master\lab07-master\test.py", line 20, in test_list_int
    contacts = Contacts(filename='t99.dat')
NameError: name 'Contacts' is not defined

======================================================================
ERROR: test_list_int (__main__.Test02_AddContact)
*** Test02 *** GIVEN: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates']} AND contacts = Contacts(filename='t99.dat') *** FUNCTION CALL: r = contacts.add_contact(id = '7145551212', first_name = 'Richard', last_name = 'Stallman') *** EXPECT: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates'], '7145551212': ['Richard', 'Stallman']} ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\edmar\OneDrive\Documents\CSUF Fall 2024\Python\Assignments\Assignment 7\lab07-master\lab07-master\test.py", line 36, in test_list_int
    contacts = Contacts(filename='t99.dat')
NameError: name 'Contacts' is not defined

======================================================================
ERROR: test_list_int (__main__.Test03_ModifyContact)
*** Test03 *** GIVEN: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates']} AND contacts = Contacts(filename='t99.dat') *** FUNCTION CALL: contacts.modify_contact(id = '7145551111', first_name = 'Richard', last_name = 'Stallman') *** EXPECT: filename t99.dat = {'5625553333': ['Bill', 'Gates'], '7145551111': ['Richard', 'Stallman']} ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\edmar\OneDrive\Documents\CSUF Fall 2024\Python\Assignments\Assignment 7\lab07-master\lab07-master\test.py", line 49, in test_list_int
    contacts = Contacts(filename='t99.dat')
NameError: name 'Contacts' is not defined

======================================================================
ERROR: test_list_int (__main__.Test04_ModifyContact)
*** Test04 *** GIVEN: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates']} AND contacts = Contacts(filename='t99.dat') *** FUNCTION CALL: r = contacts.modify_contact(id = '7145559999', first_name = 'Richard', last_name = 'Stallman') *** EXPECT: r = 'error' ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\edmar\OneDrive\Documents\CSUF Fall 2024\Python\Assignments\Assignment 7\lab07-master\lab07-master\test.py", line 65, in test_list_int
    contacts = Contacts(filename='t99.dat')
NameError: name 'Contacts' is not defined

======================================================================
ERROR: test_list_int (__main__.Test05_DeleteContact)
*** Test05 *** GIVEN: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates']} AND contacts = Contacts(filename='t99.dat') *** FUNCTION CALL: contacts.delete_contact(id = '7145551111') *** EXPECT: filename t99.dat = {'5625553333': ['Bill', 'Gates']} ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\edmar\OneDrive\Documents\CSUF Fall 2024\Python\Assignments\Assignment 7\lab07-master\lab07-master\test.py", line 78, in test_list_int
    contacts = Contacts(filename='t99.dat')
NameError: name 'Contacts' is not defined

======================================================================
ERROR: test_list_int (__main__.Test06_DeleteContact)
*** Test06 *** GIVEN: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates']} AND contacts = Contacts(filename='t99.dat') *** FUNCTION CALL: r = contacts.delete_contact(id = '7145551111') *** EXPECT: r = 'error' ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\edmar\OneDrive\Documents\CSUF Fall 2024\Python\Assignments\Assignment 7\lab07-master\lab07-master\test.py", line 94, in test_list_int
    contacts = Contacts(filename='t99.dat')
NameError: name 'Contacts' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.003s

FAILED (errors=6)
